-- ==============================================================================
-- SKRIP SQL SUPABASE UNTUK APLIKASI CEK BARKOT GUDANG TEMBAKAU
-- ==============================================================================
-- Cara Pakai:
-- 1. Buka dashboard Supabase Anda di https://supabase.com
-- 2. Pilih Project Anda -> Klik menu "SQL Editor" di bilah kiri
-- 3. Tempel (Paste) seluruh skrip di bawah ini, lalu klik tombol "RUN" (Jalankan)
-- ==============================================================================

-- 1. Buat Tabel Data Barkot Harian
CREATE TABLE IF NOT EXISTS public.barkot_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tanggal DATE NOT NULL,                         -- Format: YYYY-MM-DD (misal: 2026-08-27)
    no_gud INTEGER NOT NULL,                       -- Nomor Gudang (misal: 107)
    grade TEXT,                                    -- Grade Tembakau (misal: 68)
    barkot TEXT,                                   -- Nomor Barcode / Barkot (misal: 943605)
    kg NUMERIC,                                    -- Berat Kg (misal: 50)
    is_done BOOLEAN DEFAULT FALSE,                 -- Status: TRUE jika sudah dibarkot
    done_at TIMESTAMP WITH TIME ZONE,              -- Waktu saat dicentang di lapangan
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()),
    
    -- Mencegah duplikasi: dalam 1 tanggal, 1 nomor gudang hanya boleh ada 1 baris
    CONSTRAINT unique_tanggal_nogud UNIQUE (tanggal, no_gud)
);

-- 2. Buat Index untuk performa pencarian kilat per tanggal
CREATE INDEX IF NOT EXISTS idx_barkot_tanggal ON public.barkot_data (tanggal);
CREATE INDEX IF NOT EXISTS idx_barkot_nogud ON public.barkot_data (no_gud);

-- 3. Aktifkan Row Level Security (RLS) & Berikan Izin Akses Publik
ALTER TABLE public.barkot_data ENABLE ROW LEVEL SECURITY;

-- Buat Policy agar web di HP mandor lapangan bisa membaca, menambah, dan mengubah status
DROP POLICY IF EXISTS "Public Full Access Barkot" ON public.barkot_data;
CREATE POLICY "Public Full Access Barkot" 
ON public.barkot_data 
FOR ALL 
USING (true) 
WITH CHECK (true);

-- 4. Aktifkan Fitur Realtime (agar live sync antar HP lapangan & PC kantor)
ALTER PUBLICATION supabase_realtime ADD TABLE public.barkot_data;
